print("-------------------------------------")
print("PCT SHOP")
print("-------------------------------------")
print("Watermelon              x 1 : 100 THB")
print("Orange                  x 1 : 100 THB")
print("Pineapple               x 1 : 100 THB")
print("Strawberry              x 1 : 100 THB")
print("Kiwi                    x 1 : 100 THB")
print("Cantaloupe              x 1 : 100 THB")
print("Blueberry               x 1 : 100 THB")
print("Cherry                  x 1 : 100 THB")
print("-------------------------------------")
print("Total                       : 800 THB")
print("-------------------------------------")